// Generated by `npx @cmssy/cli types` from the "cmssy" workspace.
// Do not edit: change the model in the CMS and run the command again.

/** A translatable field: one string, or one per enabled language. */
export type CmssyLocalized = string | Record<string, string>;

/**
 * What a media field reads back. Mirrors `ResolvedMedia` in @cmssy/types.
 * A single media field is `CmssyMedia | null`: a reference whose asset was
 * deleted resolves to nothing. A gallery drops such entries instead.
 */
export interface CmssyMedia {
  id: string;
  url: string | null;
  visibility: "public" | "private";
  alt?: string;
  width?: number;
  height?: number;
}

/** What a file field holds. Mirrors `FileFieldValue` in @cmssy/types. */
export type CmssyFile = string;

/** A record as `public.model.records` returns it, with `data` typed. */
export interface CmssyRecordOf<Data> {
  id: string;
  modelId: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  data: Data;
}

/**
 * FAQ Item
 *
 * Frequently-asked question rendered by the faq block on cmssy.com (CMS-1018 dogfood: block reads records via fields.relation instead of a copy repeater).
 *
 * Model slug: `faq-item`
 * Display field: `question`
 */
export interface FaqItemData {
  /** Question */
  question: CmssyLocalized;
  /** Answer */
  answer: CmssyLocalized;
  /** Order */
  order: number;
}

export type FaqItemRecord = CmssyRecordOf<FaqItemData>;

/**
 * test
 *
 * Model slug: `test`
 */
export interface TestData {
  markdown?: string;
  tabelka?: unknown;
  /** tekst sofrmatowany */
  tekst_sofrmatowany?: string;
  json?: unknown;
}

export type TestRecord = CmssyRecordOf<TestData>;

/** Every model in the workspace, by slug. */
export interface CmssyModels {
  "faq-item": FaqItemData;
  test: TestData;
}

export type CmssyModelSlug = keyof CmssyModels;

/** The typed record list `public.model.records` returns for a model. */
export interface CmssyRecordList<Slug extends CmssyModelSlug> {
  items: Array<CmssyRecordOf<CmssyModels[Slug]>>;
  total: number;
  hasMore: boolean;
}
