// Generated by `npx @cmssy/cli types` from the "cmssy" workspace.
// Do not edit: change the model in the CMS and run the command again.

/** A translatable field: one string, or one per enabled language. */
export type CmssyLocalized = string | Record<string, string>;

/** A record as `public.model.records` returns it, with `data` typed. */
export interface CmssyRecordOf<Data> {
  id: string;
  modelId: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  data: Data;
}

/**
 * FAQ Item
 *
 * Frequently-asked question rendered by the faq block on cmssy.com (CMS-1018 dogfood: block reads records via fields.relation instead of a copy repeater).
 *
 * Model slug: `faq-item`
 * Display field: `question`
 */
export interface FaqItemData {
  /** Question */
  question: CmssyLocalized;
  /** Answer */
  answer: CmssyLocalized;
  /** Order */
  order: number;
}

export type FaqItemRecord = CmssyRecordOf<FaqItemData>;

/**
 * test
 *
 * Model slug: `test`
 */
export interface TestData {
  markdown?: string;
  tabelka?: unknown;
  /** tekst sofrmatowany */
  tekst_sofrmatowany?: string;
  json?: unknown;
}

export type TestRecord = CmssyRecordOf<TestData>;

/** Every model in the workspace, by slug. */
export interface CmssyModels {
  "faq-item": FaqItemData;
  test: TestData;
}

export type CmssyModelSlug = keyof CmssyModels;

/** The typed record list `public.model.records` returns for a model. */
export interface CmssyRecordList<Slug extends CmssyModelSlug> {
  items: Array<CmssyRecordOf<CmssyModels[Slug]>>;
  total: number;
  hasMore: boolean;
}
