import type { DocsNavConfig } from "./docs-nav";

// Curated order + labels for the /docs sidebar. Membership is automatic
// (any published /docs page shows up); this only shapes section order,
// page order, and labels the humanized slug can't get right (acronyms,
// multi-word section names). New pages appear without touching this.
export const DOCS_NAV_CONFIG: DocsNavConfig = {
  root: "/docs",
  sectionOrder: [
    "start",
    "blocks",
    "rendering",
    "content",
    "auth",
    "api",
    "editor",
  ],
  labels: {
    "/docs": "Overview",
    "/docs/start": "Get Started",
    "/docs/blocks": "Blocks",
    "/docs/rendering": "Rendering",
    "/docs/content": "Content",
    "/docs/auth": "Auth",
    "/docs/api": "API & AI",
    "/docs/editor": "Editor",
    "/docs/rendering/i18n": "i18n",
    "/docs/rendering/seo": "SEO",
    "/docs/api/mcp": "MCP Server",
    "/docs/api/graphql": "GraphQL API",
    "/docs/api/cli": "CLI",
    "/docs/api/ai": "AI Features",
    "/docs/api/types": "@cmssy/types",
  },
  pageOrder: {
    start: [
      "/docs/start",
      "/docs/start/how-it-works",
      "/docs/start/quickstart",
      "/docs/start/installation",
    ],
    blocks: [
      "/docs/blocks",
      "/docs/blocks/define",
      "/docs/blocks/fields",
      "/docs/blocks/loaders",
      "/docs/blocks/theming",
      "/docs/blocks/advanced",
      "/docs/blocks/testing",
    ],
    rendering: [
      "/docs/rendering",
      "/docs/rendering/pages",
      "/docs/rendering/layouts",
      "/docs/rendering/draft-preview",
      "/docs/rendering/i18n",
      "/docs/rendering/seo",
      "/docs/rendering/scripts",
    ],
    content: [
      "/docs/content",
      "/docs/content/data-models",
      "/docs/content/media",
      "/docs/content/forms",
      "/docs/content/user-properties",
    ],
    auth: [
      "/docs/auth",
      "/docs/auth/members",
      "/docs/auth/roles",
      "/docs/auth/api-tokens",
    ],
    api: [
      "/docs/api",
      "/docs/api/mcp",
      "/docs/api/graphql",
      "/docs/api/cli",
      "/docs/api/ai",
      "/docs/api/types",
    ],
    editor: [
      "/docs/editor",
      "/docs/editor/page-builder",
      "/docs/editor/pages",
      "/docs/editor/branding",
      "/docs/editor/workspaces",
      "/docs/editor/account",
    ],
  },
};
